[build]
  command = "cd \"Alternativa 2 - Ecommerce B2B Simplificado/app\" && npm run build"
  publish = "Alternativa 2 - Ecommerce B2B Simplificado/app/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NEXT_USE_NETLIFY_EDGE = "true"

